# Example workflow for QMS repositories (SOPs, policies, work instructions)
# Copy this file to .github/workflows/qms-validate.yml in your QMS repo

name: QMS Validation

on:
  pull_request:
    paths:
      - 'docs/**'

  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: PactoSigna/qms-actions@v1
        with:
          type: qms
          mode: pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  export:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: PactoSigna/qms-actions@v1
        with:
          type: qms
          mode: release
          # Uncomment to enable Part 11 features (signatures, audit trails):
          # pactosigna-api-key: ${{ secrets.PACTOSIGNA_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
