import type {
  ChangelogEntry,
  Document,
  RiskMatrix,
  TraceabilityCoverage,
  ValidationWarning,
} from '../types.js';
import { renderRiskMatrixMarkdown } from './risk-matrix.js';

export interface PrCommentData {
  repoType: string;
  changedDocuments: Document[];
  warnings: ValidationWarning[];
  traceability: TraceabilityCoverage[];
  changelog: ChangelogEntry[];
  riskMatrix?: RiskMatrix | null;
}

/**
 * Generate the PR comment markdown body.
 */
export function renderPrComment(data: PrCommentData): string {
  const lines: string[] = [];

  const warningCount = data.warnings.length;
  const typeName = data.repoType === 'device' ? 'Device' : 'QMS';

  lines.push('## QMS Validation Report');
  lines.push('');
  lines.push(
    `**Type:** ${typeName} | **Docs changed:** ${data.changedDocuments.length} | **Total warnings:** ${warningCount}`
  );
  lines.push('');

  // Changed Documents table
  if (data.changedDocuments.length > 0) {
    lines.push('### Changed Documents');
    lines.push('');
    lines.push('| Document | Title | Status |');
    lines.push('|----------|-------|--------|');

    for (const doc of data.changedDocuments) {
      const docWarnings = data.warnings.filter((w) => w.file === doc.filePath);
      const status =
        docWarnings.length > 0
          ? `${docWarnings.length} warning${docWarnings.length > 1 ? 's' : ''}`
          : 'Clean';
      lines.push(`| ${doc.id} | ${doc.title} | ${status} |`);
    }
    lines.push('');
  }

  // Warnings table
  if (warningCount > 0) {
    lines.push('### Warnings');
    lines.push('');
    lines.push('| File | Rule | Message |');
    lines.push('|------|------|---------|');
    for (const warning of data.warnings) {
      lines.push(`| \`${warning.file}\` | \`${warning.rule}\` | ${warning.message} |`);
    }
    lines.push('');
  }

  // Traceability Summary (device only)
  if (data.traceability.length > 0) {
    lines.push('### Traceability Summary');
    lines.push('');
    lines.push('| Chain | Coverage | Delta |');
    lines.push('|-------|----------|-------|');
    for (const chain of data.traceability) {
      lines.push(`| ${chain.chainName} | ${chain.coveragePercent}% | — |`);
    }
    lines.push('');
  }

  // Risk summary (device only)
  if (data.riskMatrix) {
    lines.push(renderRiskMatrixMarkdown(data.riskMatrix));
    lines.push('');
  }

  // Changelog
  if (data.changelog.length > 0) {
    lines.push('### Changelog (this PR)');
    lines.push('');
    lines.push('| Commit | Documents |');
    lines.push('|--------|-----------|');
    for (const entry of data.changelog) {
      lines.push(
        `| \`${entry.commitSha.substring(0, 7)}\` ${entry.commitMessage} | ${entry.documentIds.join(', ')} |`
      );
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(
    '*Generated by [PactoSigna QMS Actions](https://github.com/PactoSigna/qms-actions) · [Get Part 11 compliance →](https://pactosigna.com)*'
  );

  return lines.join('\n');
}

/** Marker used to identify our comment for updates */
export const COMMENT_MARKER = '<!-- pactosigna-qms-actions -->';

/**
 * Build the full comment body with hidden marker for update-in-place.
 */
export function buildCommentBody(data: PrCommentData): string {
  return `${COMMENT_MARKER}\n${renderPrComment(data)}`;
}
