import type {
  DocumentIndex,
  GapEntry,
  RiskMatrix,
  TraceabilityCoverage,
  ChangelogEntry,
} from '../types.js';
import { renderRiskMatrixMarkdown } from './risk-matrix.js';

/**
 * Render full PTA/PRA traceability report as markdown.
 * Used for PR comments and as input for PDF generation.
 */
export function renderTraceabilityReportMarkdown(
  index: DocumentIndex,
  coverage: TraceabilityCoverage[],
  gaps: GapEntry[],
  riskMatrix: RiskMatrix | null,
  changelog: ChangelogEntry[],
  releaseTag?: string
): string {
  const lines: string[] = [];

  // Cover section
  lines.push('# Traceability Report');
  lines.push('');
  if (releaseTag) {
    lines.push(`**Release:** ${releaseTag}`);
  }
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push(`**Total Documents:** ${index.byId.size}`);
  lines.push('');

  // Document Manifest
  lines.push('## Document Manifest');
  lines.push('');
  lines.push('| ID | Title | Type | Status | File |');
  lines.push('|----|-------|------|--------|------|');
  for (const [, doc] of index.byId) {
    lines.push(
      `| ${doc.id} | ${doc.title} | ${formatTypeName(doc.docType)} | ${doc.status} | ${doc.filePath} |`
    );
  }
  lines.push('');

  // Traceability Matrix
  if (coverage.length > 0) {
    lines.push('## Traceability Matrix');
    lines.push('');
    lines.push('| Chain | Coverage | Covered | Total |');
    lines.push('|-------|----------|---------|-------|');
    for (const chain of coverage) {
      lines.push(
        `| ${chain.chainName} | ${chain.coveragePercent}% | ${chain.coveredSources} | ${chain.totalSources} |`
      );
    }
    lines.push('');
  }

  // Risk Matrix
  if (riskMatrix) {
    lines.push('## Risk Analysis (ISO 14971)');
    lines.push('');
    lines.push(renderRiskMatrixMarkdown(riskMatrix));
    lines.push('');
  }

  // Gap Analysis
  if (gaps.length > 0) {
    lines.push('## Gap Analysis');
    lines.push('');
    lines.push(`**Total gaps found:** ${gaps.length}`);
    lines.push('');
    lines.push('| Document | Gap Type | Message | Severity |');
    lines.push('|----------|----------|---------|----------|');
    for (const gap of gaps) {
      lines.push(`| ${gap.documentId} | ${gap.gapType} | ${gap.message} | ${gap.severity} |`);
    }
    lines.push('');
  } else {
    lines.push('## Gap Analysis');
    lines.push('');
    lines.push('No traceability gaps detected.');
    lines.push('');
  }

  // Changelog
  if (changelog.length > 0) {
    lines.push('## Changelog');
    lines.push('');
    lines.push('| Commit | Message | Documents |');
    lines.push('|--------|---------|-----------|');
    for (const entry of changelog) {
      lines.push(
        `| ${entry.commitSha.substring(0, 7)} | ${entry.commitMessage} | ${entry.documentIds.join(', ')} |`
      );
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(
    '*Generated by [PactoSigna QMS Actions](https://github.com/PactoSigna/qms-actions)*'
  );

  return lines.join('\n');
}

/**
 * Render the traceability report as HTML for PDF generation.
 */
export function renderTraceabilityReportHtml(
  index: DocumentIndex,
  coverage: TraceabilityCoverage[],
  gaps: GapEntry[],
  riskMatrix: RiskMatrix | null,
  changelog: ChangelogEntry[],
  releaseTag?: string
): string {
  const lines: string[] = [];

  lines.push('<!DOCTYPE html>');
  lines.push('<html><head><meta charset="utf-8">');
  lines.push('<style>');
  lines.push(REPORT_CSS);
  lines.push('</style></head><body>');

  // Cover page
  lines.push('<div class="cover-page">');
  lines.push('<h1>Traceability Report</h1>');
  if (releaseTag) lines.push(`<p class="release-tag">${releaseTag}</p>`);
  lines.push(`<p>Generated: ${new Date().toISOString()}</p>`);
  lines.push(`<p>Total Documents: ${index.byId.size}</p>`);
  lines.push('</div>');

  // Manifest
  lines.push('<h2>Document Manifest</h2>');
  lines.push('<table><thead><tr>');
  lines.push('<th>ID</th><th>Title</th><th>Type</th><th>Status</th>');
  lines.push('</tr></thead><tbody>');
  for (const [, doc] of index.byId) {
    lines.push(
      `<tr><td>${doc.id}</td><td>${doc.title}</td><td>${formatTypeName(doc.docType)}</td><td>${doc.status}</td></tr>`
    );
  }
  lines.push('</tbody></table>');

  // Traceability
  if (coverage.length > 0) {
    lines.push('<h2>Traceability Matrix</h2>');
    lines.push('<table><thead><tr>');
    lines.push('<th>Chain</th><th>Coverage</th><th>Covered</th><th>Total</th>');
    lines.push('</tr></thead><tbody>');
    for (const chain of coverage) {
      const cssClass = chain.coveragePercent === 100 ? 'good' : chain.coveragePercent >= 80 ? 'warn' : 'bad';
      lines.push(
        `<tr><td>${chain.chainName}</td><td class="${cssClass}">${chain.coveragePercent}%</td><td>${chain.coveredSources}</td><td>${chain.totalSources}</td></tr>`
      );
    }
    lines.push('</tbody></table>');
  }

  // Risk matrix
  if (riskMatrix) {
    lines.push('<h2>Risk Analysis (ISO 14971)</h2>');
    lines.push(renderRiskGridHtml(riskMatrix.inherent, 'Inherent Risk'));
    lines.push(renderRiskGridHtml(riskMatrix.residual, 'Residual Risk'));

    lines.push('<h3>Risk Summary</h3>');
    lines.push('<table><thead><tr><th>Status</th><th>Count</th></tr></thead><tbody>');
    lines.push(`<tr><td class="good">Acceptable</td><td>${riskMatrix.summary.acceptable}</td></tr>`);
    lines.push(`<tr><td class="warn">Review Required</td><td>${riskMatrix.summary.reviewRequired}</td></tr>`);
    lines.push(`<tr><td class="bad">Unacceptable</td><td>${riskMatrix.summary.unacceptable}</td></tr>`);
    lines.push('</tbody></table>');
  }

  // Gaps
  lines.push('<h2>Gap Analysis</h2>');
  if (gaps.length > 0) {
    lines.push(`<p>Total gaps: ${gaps.length}</p>`);
    lines.push('<table><thead><tr>');
    lines.push('<th>Document</th><th>Gap Type</th><th>Message</th>');
    lines.push('</tr></thead><tbody>');
    for (const gap of gaps) {
      lines.push(`<tr><td>${gap.documentId}</td><td>${gap.gapType}</td><td>${gap.message}</td></tr>`);
    }
    lines.push('</tbody></table>');
  } else {
    lines.push('<p>No traceability gaps detected.</p>');
  }

  // Changelog
  if (changelog.length > 0) {
    lines.push('<h2>Changelog</h2>');
    lines.push('<table><thead><tr><th>Commit</th><th>Message</th><th>Documents</th></tr></thead><tbody>');
    for (const entry of changelog) {
      lines.push(
        `<tr><td><code>${entry.commitSha.substring(0, 7)}</code></td><td>${escapeHtml(entry.commitMessage)}</td><td>${entry.documentIds.join(', ')}</td></tr>`
      );
    }
    lines.push('</tbody></table>');
  }

  lines.push('<div class="footer">');
  lines.push('Generated by PactoSigna QMS Actions');
  lines.push('</div>');
  lines.push('</body></html>');

  return lines.join('\n');
}

function renderRiskGridHtml(grid: number[][], title: string): string {
  const probLabels = ['Frequent', 'Likely', 'Possible', 'Unlikely', 'Remote'];
  const sevLabels = ['Negligible', 'Minor', 'Moderate', 'Major', 'Catastrophic'];

  const lines: string[] = [];
  lines.push(`<h3>${title}</h3>`);
  lines.push('<table class="risk-grid"><thead><tr><th>P \\ S</th>');
  for (const sev of sevLabels) {
    lines.push(`<th>${sev}</th>`);
  }
  lines.push('</tr></thead><tbody>');

  for (let p = grid.length - 1; p >= 0; p--) {
    lines.push(`<tr><td><strong>${probLabels[grid.length - 1 - p]}</strong></td>`);
    for (let s = 0; s < grid[p].length; s++) {
      const count = grid[p][s];
      const cellClass = getRiskCellClass(p + 1, s + 1);
      lines.push(`<td class="${cellClass}">${count > 0 ? count : '-'}</td>`);
    }
    lines.push('</tr>');
  }
  lines.push('</tbody></table>');

  return lines.join('\n');
}

function getRiskCellClass(prob: number, sev: number): string {
  const score = prob * sev;
  if (score >= 15) return 'risk-high';
  if (score >= 8) return 'risk-medium';
  return 'risk-low';
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function formatTypeName(type: string): string {
  return type
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

const REPORT_CSS = `
  body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #333; }
  h1 { color: #1a237e; border-bottom: 2px solid #1a237e; padding-bottom: 8px; }
  h2 { color: #283593; margin-top: 32px; }
  h3 { color: #3949ab; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 13px; }
  th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
  th { background: #f5f5f5; font-weight: 600; }
  .cover-page { text-align: center; margin-bottom: 48px; padding: 48px 0; }
  .cover-page h1 { font-size: 28px; }
  .release-tag { font-size: 20px; color: #1a237e; font-weight: 600; }
  .good { color: #2e7d32; font-weight: 600; }
  .warn { color: #f57f17; font-weight: 600; }
  .bad { color: #c62828; font-weight: 600; }
  .risk-grid td { text-align: center; min-width: 60px; }
  .risk-high { background: #ffcdd2; color: #c62828; font-weight: 600; }
  .risk-medium { background: #fff9c4; color: #f57f17; font-weight: 600; }
  .risk-low { background: #c8e6c9; color: #2e7d32; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 12px; color: #999; text-align: center; }
  code { background: #f5f5f5; padding: 2px 4px; border-radius: 3px; font-size: 12px; }
`;
